use devdb;
drop table if exists TODO;
CREATE TABLE TODO(
  ID int primary key auto_increment,
  CONTENT VARCHAR(256) NOT NULL,
  IS_DONE  numeric(1) DEFAULT 0
);
-- CREATE
INSERT INTO TODO (CONTENT) VALUES ('flask');
INSERT INTO TODO (CONTENT) VALUES ('프로젝트발표');
INSERT INTO TODO (CONTENT) VALUES ('포트폴리오작성');

-- READ
SELECT * FROM TODO ORDER BY ID;
SELECT * FROM TODO WHERE ID = 1;

-- next_id
SELECT MAX(ID)+1 FROM TODO;

-- UPDATE
UPDATE TODO SET CONTENT='바꿀내용', IS_DONE=1 WHERE ID=1;

-- DELETE
DELETE FROM TODO WHERE ID=2;
COMMIT;