--[V]시퀀스 : 순차번호 생성기. 인위적인 PK사용용도 

DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1 -- 1부터 시작(기본값)
    INCREMENT BY 1 --1씩 증가(기본값)
    MAXVALUE 9999 --최대값
    MINVALUE 1
    NOCACHE
    NOCYCLE;
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; --다음 순차번호생성
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; --시퀀스 현재값

--EX. FRIEND 태이블 : NO;숫3-PK, NAME문 20, ADDRESS문200, LAST_MODYFY날
DROP SEQUENCE FRIEND_NO_SEQ;
CREATE SEQUENCE FRIEND_NO_SEQ MAXVALUE 999 NOCACHE NOCYCLE;
CREATE TABLE FRIEND(
    NO NUMBER(3)      PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    TEL  VARCHAR2(20) UNIQUE,
    ADDRESS VARCHAR2(200),
    LAST_MODIFY DATE DEFAULT SYSDATE
);
INSERT INTO FRIEND (NO,NAME,TEL,ADDRESS)
    VALUES (friend_no_seq.nextval,'홍길동',NULL,'관악구 신림동');
SELECT * FROM FRIEND;
INSERT INTO FRIEND 
    VALUES (friend_no_seq.nextval,'성춘향','010-9999-9999','남원',SYSDATE);
SELECT * FROM FRIEND;






