--[IV] DCL,DDL,DML
/* SQL 
(1) DCL : 사용자 계정생성(CREATE USER), 권한부여(GRANT), 권한박탈(REVOKE), 사용자 계정삭제(DROP USER)
          트렌젝션 명령어 (ROLLBACK, COMMIT)
(2) DDL : 테이블 생성(CREATE TABLE), 태이블구조변경(ALTER TABLE), 태이블 삭제(DROP TABLE)
(3) DML :CRUD
        입력(INSERT), 수정(UPDATE), 삭제(DELETE)-취소(ROLLBACK)가능
        검색(SELECT),
*/
---------------
--- ★ DDL ★---
---------------
--1. 태이블 생성(CREATE TABLE 태이블명...) : 태이블 구조 정의 
    --ORACLE 타입 : NUMBER(38이하의 자릿수),DATE,VARCHAR2(4000이하의 바이트수),CLOB
CREATE TABLE BOOK(
    BOOKID    NUMBER(4)PRIMARY KEY,    --BOOKID필드의 타입은 숫자4자리
    BOOKNAME  VARCHAR2(30), --BOOKNAME필드의 타입은 문자 30BYTE(한글 1자=3BYTE)
    PUBLISHER VARCHAR2(30), 
    RDATE     DATE,         --RDATE 필드의 타입은 DATE(날짜+시간)
    PRICE     NUMBER(8,2),  --PRICE필드의 타입은 숫자 전체8자리 중 소숫점 2자리
    PRIMARY KEY(BOOKID)     --제약조건 : BOOKID를 주키(PRIMARY KEY)로
);
--DESC BOOK;
--SELECT * FROM BOOK;
--DROP TABLE BOOK; -- 2. 태이블삭제(DROP TABLE 태이블명


CREATE TABLE BOOK(
    BOOKID    NUMBER(4)PRIMARY KEY, --제약조건   
    BOOKNAME  VARCHAR2(30), 
    PUBLISHER VARCHAR2(30), 
    RDATE     DATE,         
    PRICE     NUMBER(8,2),  
         
);
--DROP TABLE BOOK;
--DROP TABLE DEPT
--DEPT와 유사한 DEPT01 태이블/ EMP와 유사한 EMP01태이블 생성
-- DEPT01 : DEPTNO(PK:숫자(2)), DNAME(문14byte),LOC(문13byte)

CREATE TABLE DEPT01(
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC   VARCHAR2(13)  
);
SELECT * FROM DEPT01;
INSERT INTO DEPT01 VALUES(10,'재무','신림');--트렌젝션에 쌓아놓은 데이터
SELECT * FROM DEPT01;
ROLLBACK; --트렌젝션에 쌓인 명령어 날리기
--EMP01;EMPNO(PK:숫자(4), ENAME(문14),JOB(문9),MGR(숫4),HIREDATE(날),SAL(숫7.2),DEPTNO(숫2;FK)
DROP TABLE EMP01;
CREATE TABLE EMP01(
    EMPNO NUMBER(4), 
    ENAME VARCHAR2(10),
    JOB   VARCHAR2(9),
    MGR   NUMBER(4),
    HIREDATE DATE,
    SAL   NUMBER(7,2),
    COMM  NUMBER(7,2),
    DEPTNO NUMBER(2), 
    PRIMARY KEY(EMPNO), --주키 제약조건(NULL불가, 유일한값)
    FOREIGN KEY(DEPTNO) REFERENCES DEPT01(DEPTNO) --외래키(FOREIGN KEY)제약조건   
);

SELECT * FROM DEPT01;
INSERT INTO DEPT01 VALUES(10,'재무','신림');--트렌젝션에 쌓아놓은 데이터
INSERT INTO EMP01 VALUES (1000,'홍길동','NULL','NULL','NULL','NULL','NULL',10);
SELECT * FROM DEPT01;
COMMIT;--트렌젝션이 쌓여있는 명령어를 오라클 적용
DROP TABLE DEPT01; --참조하는 태이블이 있을경우, 삭제 불가(삭제하려면 참조하는 태이블을 DROP한후 DROP추천)
DROP TABLE DEPT01 CASCADE CONSTRAINTS;

---------------
--- ★ DML ★---
---------------
--1.INSERT INTO 태이블명 VALUSE (값1,값2,...값N);
  --INSERT INTO 태이블명 (필드명1, 필드명2...) VALUES(값1,값2,...값N); 
  
SELECT * FROM DEPT01;
INSERT INTO DEPT01 VALUES (50,'법무','서초');
INSERT INTO DEPT01 (LOC,DNAME,DEPTNO) VALUES('신림','인사',60);
INSERT INTO DEPT01 (DEPTNO,DNAME,LOC) VALUES(70,'영업',NULL); --명시적 NULL입력
INSERT INTO DEPT01 (DEPTNO,DNAME) VALUES(80,'고객지원');--묵시적 NULL입력
SELECT * FROM DEPT01;
    --서브쿼리를 이용한 INSERT
    --EX. DEPT태이블의 20~40번 부서정보를 DEPT01에 INSERT
    INSERT INTO DEPT01 SELECT * FROM DEPT WHERE DEPTNO >= 20;
    SELECT * FROM DEPT01;

-- DDL 연습문제 page1(DDL,INSERT)
/*
•다음과 같은 구조로 SAM01 테이블을 생성하시오 . 같은 이름의 테이블이 존재할 수 있으니 , DROP
TABLE 로 삭제 후 생성하시오
–SAM01 의 구조 (EMPNO 를 주키로
•EMPNO( 사번 ) NUMBER(4)
•ENAME( 이름 ) VARCHAR2(10)
•JOB( 직책 ) VARCHAR2(9)
•SAL( 급여 ) NUMBER(7,2)
•EMP 에 저장된 사원 중 10 번 부서 소속 사원의 정보를 추가한다
*/
DROP TABLE SAM01;
CREATE TABLE SAM01(
    EMPNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    SAL NUMBER(7,2)
);
INSERT INTO SAM01 VALUES (1000,'APPLE','POLICE',10000);
INSERT INTO SAM01 VALUES (1010,'BANANA','NURSE',15000);
INSERT INTO SAM01 VALUES (1020,'ORANGE','DOCTOR',25000);
INSERT INTO SAM01 (EMPNO,ENAME,SAL)
    VALUES (1030,'VERY',25000);
INSERT INTO SAM01 (EMPNO,ENAME,SAL)
    VALUES (1040,'CAT',20000);
SELECT * FROM SAM01;
SELECT EMPNO,ENAME,JOB,SAL FROM EMP WHERE DEPTNO=10;--SAM01에 INSERT할 내용
INSERT INTO SAM01 SELECT EMPNO,ENAME,JOB,SAL FROM EMP WHERE DEPTNO=10;

COMMIT;

--2.UPDATE 테이블명 SET 필드명1=값1[,필드명2=값2,...필드명N=값N]WHERE조건]
DROP TABLE EMP01;
--서브쿼리를 이용한 태이블 생성(제약조건이 제외된 데이터만 가져옴)
CREATE TABLE EMP01 AS SELECT * FROM EMP WHERE DEPTNO IN (20,30);
SELECT * FROM EMP01;
DESC EMP01;
    --EX.부서번호를 99번으로 수정
UPDATE EMP01 SET DEPTNO=99;
SELECT * FROM EMP01;
ROLLBACK; --트렌젝션 명령어들 취소
SELECT * FROM EMP01;
    --EX. 모든 사원의 급여(SAL)를 10%인상
UPDATE EMP01 SET SAL=SAL*1.1;
SELECT * FROM EMP01;
    --EX.급여(SAL)가 1200미만인 직원의 급여를 100$씩 인상
UPDATE EMP01 SET SAL=SAL+100 WHERE SAL<1200
SELECT * FROM EMP01;
    --EX. SMITH의 부서번호를 30, JOB을 'SALESMAN', SAL과 COMM을 500$씩 인상, 입사일을 오늘로, 상사는 BLACK로
UPDATE EMP01 
    SET DEPTNO=30, 
        JOB='SALESMAN', 
        SAL=SAL+500, 
        COMM=NVL(COMM,0)+500,
        --HIREDATE = TO_DATE('26/08/21','RR/MM/DD),
        HIREDATE = SYSDATE,
        MGR = (SELECT EMPNO FROM EMP01 WHERE ENAME='BLAKE')
    WHERE ENAME = 'SMITH';
SELECT * FROM EMP01 WHERE ENAME='SMITH';

--3.DELETE FROM 테이블명[WHERE조건];
    SELECT * FROM EMP01;
    DELETE FROM EMP01;
    SELECT * FROM EMP01;
    ROLLBACK;
    SELECT * FROM EMP01;
    
    --EX. EMP01에서 'FORD'직원을 퇴사
    DELETE FROM EMP01 WHERE ENAME='FORD';
    
    --EX. SAM01에서 JOB이 정해지지않은 사원을 삭제
    DELETE FROM SAM01 WHERE JOB IS NULL; 
    SELECT * FROM SAM01;
    
    --EX. EMP01에서 30번 부서 직원을 삭제
    DELETE FROM EMP01 WHERE DEPTNO=30;
    SELECT * FROM EMP01;
    COMMIT;

/*DDL, DML 연습문제 page2*/

--1.아래의 구조를 만족하는 MY_DATA 테이블을 생성하시오 . 단 ID 가 PRIMARY KEY 이다

CREATE TABLE MY_DATA(
    ID NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(10),
    USERID VARCHAR2(30),
    SALARY NUMBER(10,2)
    );

--2.생성된 테이블에 위의 도표와 같은 값을 입력하는 SQL 문을 작성하시오
INSERT INTO MY_DATA VALUES (1,'Scott','scott',10000.00); 
INSERT INTO MY_DATA VALUES (2,'Ford','fford',13000.00);
INSERT INTO MY_DATA VALUES (3,'Patel','ppatel',33000.00);
INSERT INTO MY_DATA VALUES (4,'Report','rreport',23500.00);
INSERT INTO MY_DATA VALUES (5,'Good','ggood',44450.00);
SELECT * FROM MY_DATA;

--3.TO_CHAR 내장 함수를 이용하여 입력한 자료를 위의 도표와 같은 형식으로 출력하는SQL 문을 작성하시오
SELECT ID,ENAME,USERID, TO_CHAR(SALARY,'99,999.00') AS SALARY FROM MY_DATA;

--4.자료를 영구적으로 데이터베이스에 등록하는 명령어를 작성하시오
COMMIT;

--5.ID 가 3 번인 사람의 급여를 65000.00 으로 갱신하고 영구적으로 데이터베이스에 반영하라
UPDATE MY_DATA SET SALARY=65000.00 WHERE ID=3;
COMMIT;

--6.NAME 이 Ford 인 사람을 삭제하고 영구적으로 데이터베이스에 반영하라
DELETE FROM MY_DATA WHERE ENAME='Ford';
SELECT * FROM MY_DATA;
commit;

--7.SALARY 가 15,000.00 이하인 사람의 급여를 15,000.00 으로 변경하라
UPDATE MY_DATA SET SALARY = 15000.00 WHERE SALARY<=15000.00;
SELECT * FROM MY_DATA;

--8.위에서 생성한 테이블을 삭제하라
DROP TABLE MY_DATA;


/*DML 연습문제 page3*/
/*1. EMP 테이블과 같은 구조와 같은 내용의 테이블 EMP01 을 (생성 테이블이 있을시 제거한 후)하고, 모든 사원의 부서번호를 30 번으로 수정합니다*/
DROP TABLE EMP01 CASCADE CONSTRAINTS;
SELECT * FROM EMP;

CREATE TABLE EMP01 AS SELECT * FROM EMP;
UPDATE EMP01 SET DEPTNO = 30;
SELECT * FROM EMP01;

/*2. EMP01 테이블의 모든 사원의 급여를 10% 인상시키는 UPDATE 문을 작성*/
UPDATE EMP01 SET SAL=SAL*1.1;
SELECT * FROM EMP01;

/*3. 급여가 3000 이상인 사원만 급여를 10% 인상*/
UPDATE EMP01 SET SAL=SAL*1.1 WHERE SAL<3000;
SELECT * FROM EMP01;

/*4. EMP01 테이블에서 'DALLAS' 에서 근무하는 직원들의 월급 을 1000 인상*/
UPDATE EMP01 SET SAL = SAL+1000
    WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='DALLAS');

/*5. SCOTT 사원의 부서번호는 20 번으로 , 직급은 MANAGER 로 한꺼번에 수정*/
UPDATE EMP01 SET DEPTNO = SAL+1000
    WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='DALLAS');

--6. 부서명이 RESEARCH 인 사원을 모두 삭 제하는 SQL 작성
--7. 사원명이 ‘ 인 사원을 삭제하는 SQL 작성
--8. SAM01 테이블에서 JOB 이 NULL 인 사원을 삭제하시오
--9. SAM01 테이블에서 ENAME 이 ORANGE 인 사원을 삭제하시오
--10. 급여가 1500 이하인 사람의 급여를 1500 으로 수정
--11. JOB 이 ‘ 인 사원의 급여를 10% 인하하시오


-------------------
--- ★ 제약조건 ★---
-------------------
    -- (1) PRIMARY KEY : 태이블의 각 행을 유일한 값으로 식별하기 위한 필드
    -- (2) FORRIGN KEY : 태이블의 열이 다른 태이블의 열을 참조
    -- (3) NOT NULL : NULL을 포함하지 않는다.
    -- (4) UNIQUE : 모든 행의 값이 유일해야함. NULL값은 허용(NULL은 여러개 가능)
    -- (5) CHECK(조건) : 해당 조건이 만족해야 한다. NULL값은 허용
    -- DEFAULT 기본값 : 기본값 설정(INSERT할 경우, 해당 열의 데이터를 입력하지 않으면 NULL이 들어가지않고 기본값)

--DEPT1 & EMP1
DROP TABLE DEPT1; 
DROP TABLE ENP1;

CREATE TABLE DEPT1(
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME VARCHAR2(14) UNIQUE,
    LOC VARCHAR2(13) NOT NULL
);
INSERT INTO DEPT1 SELECT * FROM DEPT;
SELECT * FROM DEPT;

INSERT INTO DEPT1 VALUES (40,'법무','SEOUL');--PK 제약조건 에러 

UPDATE DEPT1 SET DNAME='SALES' WHERE DEPTNO=40;--UNIQUE제약조건 에러
INSERT INTO DEPT1 (DEPTNO,DNAME) VALUES (50,'전산'); --묵시적으로 LOC에 NULL을 입력-NOT NULL제약조건 에러


CREATE TABLE EMP1(
    EMPTNO NUMBER(4) PRIMARY KEY,
    ENAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9), 
    MGR NUMBER(4),
    HIREDATE DATE DEFAULT SYSDATE,
    SAL NUMBER(7,2) CHECK(SAL>0),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2)REFERENCES DEPT1(DEPTNO)
);

INSERT INTO EMP1 (EMPTNO,ENAME, DEPTNO) VALUES (1000,'HONG',10);--HIREDATE에 SYSDATE기본값 입력
INSERT INTO EMP1 (EMPTNO,ENAME,SAL,DEPTNO) 
    VALUES (1001,'HONG',0,10);
INSERT INTO EMP1 (EMPTNO,ENAME,SAL,DEPTNO) 
    VALUES (1002,'HONG',100,50);
INSERT INTO EMP1 (EMPTNO,ENAME,SAL,DEPTNO) 
    VALUES (1002,'HONG',100,10);
SELECT * FROM EMP1;









